/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vku.Design;

/**
 *
 * @author admin!
 */
public class TC_Admin extends javax.swing.JFrame {

    /**
     * Creates new form TC_Server
     */
    public TC_Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        QLDH = new javax.swing.JLabel();
        TK = new javax.swing.JLabel();
        Banking = new javax.swing.JLabel();
        TL = new javax.swing.JLabel();
        QLSP = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bg = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        QLDH.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        QLDH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vku/icon/Ecommerce-Product-icon.png"))); // NOI18N
        QLDH.setText("Quản lý đơn hàng");
        QLDH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QLDHMouseClicked(evt);
            }
        });

        TK.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        TK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vku/icon/Open-folder-accept-icon.png"))); // NOI18N
        TK.setText("Thống kê");
        TK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TKMouseClicked(evt);
            }
        });

        Banking.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Banking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vku/icon/Check-icon.png"))); // NOI18N
        Banking.setText("Kiểm tra tài khoản");
        Banking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BankingMouseClicked(evt);
            }
        });

        TL.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        TL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vku/icon/edit-icon.png"))); // NOI18N
        TL.setText("Thiết lập");
        TL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TLMouseClicked(evt);
            }
        });

        QLSP.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        QLSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vku/icon/manager.png"))); // NOI18N
        QLSP.setText("Quản lý sản phẩm");
        QLSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QLSPMouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vku/icon/Exit.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QLDH, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TK, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Banking, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TL, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(92, 92, 92)
                .addComponent(QLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(QLDH, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(TK, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(Banking, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(TL, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 830));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vku/icon/menu.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        bg.setLayout(new java.awt.BorderLayout());
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vku/icon/Thiết kế chưa có tên (3).png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1253, 828));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        openMenu();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
       closeMenu();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void QLSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QLSPMouseClicked
        taiTrang(1);
    }//GEN-LAST:event_QLSPMouseClicked

    private void QLDHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QLDHMouseClicked
        taiTrang(2);
    }//GEN-LAST:event_QLDHMouseClicked

    private void TKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TKMouseClicked
        taiTrang(3);
    }//GEN-LAST:event_TKMouseClicked

    private void BankingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BankingMouseClicked
        taiTrang(4);
    }//GEN-LAST:event_BankingMouseClicked

    private void TLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TLMouseClicked
        taiTrang(5);
    }//GEN-LAST:event_TLMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TC_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TC_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TC_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TC_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TC_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Banking;
    private javax.swing.JLabel QLDH;
    private javax.swing.JLabel QLSP;
    private javax.swing.JLabel TK;
    private javax.swing.JLabel TL;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    int width = 260;
    int height = 950;
    ThietLap_A tl;
    QLSP sp;
    QLDH dh;
    TK tk;
    Banking b;
    Edit e;

    private void openMenu() {
        new Thread(new Runnable() {
            public void run() {
                for (int i = 0; i < width; i++) {
                    jPanel1.setSize(width, height);
                    try {
                        Thread.sleep(1);
                    } catch (InterruptedException ex) {
                        ex.printStackTrace();
                    }
                }

            }

        }).start();
    }

    private void closeMenu() {
        new Thread(new Runnable() {
            public void run() {
                for (int i = width; i > 0; i--) {
                    jPanel1.setSize(i, height);
                    try {
                        Thread.sleep(1);
                    } catch (InterruptedException ex) {
                        ex.printStackTrace();
                    }
                }

            }

        }).start();
    }

    private void taiTrang(int i) {
        bg.removeAll();
        switch (i) {
            case 1:
                if (sp == null) {
                    sp = new QLSP();
                }
                bg.add(sp);

                break;
            case 2:
                if (dh == null) {
                    dh = new QLDH();
                }
                bg.add(dh);

                break;
            case 3:
                if (tk == null) {
                    tk = new TK();
                }
                bg.add(tk);

                break;
            case 4:
                if (b == null) {
                    b = new Banking();
                }
                bg.add(b);

                break;
             case 5:
                if (tl == null) {
                    tl = new ThietLap_A();
                }
                bg.add(tl);

                break;
            default:

                break;
        }
        bg.updateUI();
    }
}
